module.exports = {
    name: 'Pesca & Acuicultura',
    keywords: ['pesca', 'pescador', 'salmonicultura', 'acuicultura', 'marítimo', 'sernapesca', 'subpesca'],
    categories: {
        'Pesca Artesanal': ['artesanal', 'conapach', 'confepach', 'caleta', 'pescador artesanal'],
        'Cultivos y Áreas de Manejo': ['área de manejo', 'amerb', 'cultivo', 'alga', 'mitilicultura'],
        'Ley de Pesca': ['ley de pesca', 'fraccionamiento', 'parlamento', 'congreso', 'legislación', 'diputados', 'senado', 'comisión de pesca'],
        'Sector Pesquero': ['sector pesquero', 'subpesca', 'sernapesca', 'consejo nacional de pesca', 'fpa', 'indespa', 'institucionalidad'],
        'Pais y Sector Empresarial': ['empresarial', 'economía', 'exportación', 'mercado', 'industria', 'gremio'],
        'Pesca Industrial': ['industrial', 'sonapesca', 'asipes', 'pesca industrial', 'camanchaca', 'blumar'],
        'Salmoneras': ['salmón', 'salmonera', 'salmonicultura', 'salmonero', 'australis', 'aqua'],
        'Innovación Acuícola': ['innovación', 'tecnología', 'investigación', 'desarrollo', 'ciencia']
    },
    rssFeeds: [
        'https://www.diarioeldia.cl/rss/noticias',
        'https://www.google.com/alerts/feeds/08397670603095634428/18119852156385057077',
        'https://www.google.com/alerts/feeds/08397670603095634428/10231861125372209595',
        'https://www.google.com/alerts/feeds/08397670603095634428/10693748374007497326',
        'https://www.google.com/alerts/feeds/08397670603095634428/330466514247678387',
        'https://www.google.com/alerts/feeds/08397670603095634428/16468006218765930623',
        'https://www.google.com/alerts/feeds/08397670603095634428/2590044238413771770',
        'https://www.google.com/alerts/feeds/08397670603095634428/18339820440676763392',
        'https://www.google.com/alerts/feeds/08397670603095634428/10693748374007497711',
        'https://www.google.com/alerts/feeds/08397670603095634428/16468006218765934227',
        'https://www.google.com/alerts/feeds/08397670603095634428/10693748374007498663',
        'https://www.google.com/alerts/feeds/08397670603095634428/10693748374007498275',
        'https://mdstrm.com/feeds/grupo-copesa/informacion-privilegiada',
        'https://www.ciperchile.cl/feed/',
        'https://www.theclinic.cl/feed/',
        'https://www.elciudadano.com/feed/',
        { url: 'https://news.google.com/rss/search?q=site:emol.com+pesca&hl=es-CL&gl=CL&ceid=CL:es-419', sourceName: 'Emol' },
        { url: 'https://news.google.com/rss/search?q=site:meganoticias.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419', sourceName: 'Meganoticias' },
        { url: 'https://news.google.com/rss/search?q=site:24horas.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419', sourceName: '24 Horas' },
        { url: 'https://news.google.com/rss/search?q=site:t13.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419', sourceName: 'T13' },
        { url: 'https://news.google.com/rss/search?q=site:chvnoticias.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419', sourceName: 'CHV Noticias' },
        { url: 'https://news.google.com/rss/search?q=site:cnnchile.com+pesca&hl=es-CL&gl=CL&ceid=CL:es-419', sourceName: 'CNN Chile' },
        { url: 'https://news.google.com/rss/search?q=site:elmostrador.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419', sourceName: 'El Mostrador' },
        { url: 'https://news.google.com/rss/search?q=site:eldinamo.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419', sourceName: 'El Dínamo' },
        { url: 'https://news.google.com/rss/search?q=site:pauta.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419', sourceName: 'Pauta' },
        { url: 'https://news.google.com/rss/search?q=site:ellibero.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419', sourceName: 'El Líbero' },
        { url: "https://news.google.com/rss/search?q=site:lacuarta.com+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "La Cuarta" },
        { url: "https://news.google.com/rss/search?q=site:Lun.com+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Las Últimas Noticias" },
        { url: "https://news.google.com/rss/search?q=site:elconquistadorfm.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio El Conquistador" },
        { url: "https://news.google.com/rss/search?q=site:portalesvalparaiso.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Portales" },
        { url: "https://news.google.com/rss/search?q=site:pudahuel.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Pudahuel" },
        { url: "https://news.google.com/rss/search?q=site:arica365.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Arica365" },
        { url: "https://news.google.com/rss/search?q=site:aricatv.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Arica TV" },
        { url: "https://news.google.com/rss/search?q=site:antofagastatv.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Antofagasta TV" },
        { url: "https://news.google.com/rss/search?q=site:araucaniadiario.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Araucanía Diario" },
        { url: "https://news.google.com/rss/search?q=site:cronicachillan.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Crónica Chillán" },
        { url: "https://news.google.com/rss/search?q=site:curicoalbirrojo.com+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Curicó Albirrojo" },
        { url: "https://news.google.com/rss/search?q=site:biobiochile.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "BioBioChile" },
        { url: "https://news.google.com/rss/search?q=site:cooperativa.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Cooperativa" },
        { url: "https://news.google.com/rss/search?q=site:adnradio.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "ADN Radio" },
        { url: "https://news.google.com/rss/search?q=site:df.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Diario Financiero" },
        { url: "https://news.google.com/rss/search?q=site:hoyxhoy.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Hoy x Hoy" },
        { url: "https://news.google.com/rss/search?q=site:mercuriovalpo.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "El Mercurio Valparaíso" },
        { url: "https://news.google.com/rss/search?q=site:diariolaregion.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "La Región" },
        { url: "https://news.google.com/rss/search?q=site:elmauleinforma.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "El Maule Informa" },
        { url: "https://news.google.com/rss/search?q=site:laserenaonline.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "La Serena Online" },
        { url: "https://news.google.com/rss/search?q=site:elllanquihue.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "El Llanquihue" },
        { url: "https://news.google.com/rss/search?q=site:laprensaaustral.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "La Prensa Austral" },
        { url: "https://news.google.com/rss/search?q=site:estrellachiloe.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Estrella Chiloé" },
        { url: "https://news.google.com/rss/search?q=site:aqua.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Aqua" },
        { url: "https://news.google.com/rss/search?q=site:pescahoy.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "PescaHoy" },
        { url: "https://news.google.com/rss/search?q=site:pulso.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Pulso" },
        { url: "https://news.google.com/rss/search?q=site:estrellaarica.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Estrella Arica" },
        { url: "https://news.google.com/rss/search?q=site:diarioatacama.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Diario Atacama" },
        { url: "https://news.google.com/rss/search?q=site:australvaldivia.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Diario Austral de Los Ríos" },
        { url: "https://news.google.com/rss/search?q=site:diariochañarcillo.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "El Chañarcillo" },
        { url: "https://news.google.com/rss/search?q=site:diarioconcepcion.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Diario Concepción" },
        { url: "https://news.google.com/rss/search?q=site:diarioaysen.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Diario de Aysén" },
        { url: "https://news.google.com/rss/search?q=site:diariodeosorno.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Diario de Osorno" },
        { url: "https://news.google.com/rss/search?q=site:diariocentro.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Diario El Centro" },
        { url: "https://news.google.com/rss/search?q=site:ellongino.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Diario El Longino" },
        { url: "https://news.google.com/rss/search?q=site:elovallino.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Diario El Ovallino" },
        { url: "https://news.google.com/rss/search?q=site:australtemuco.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "El Austral de la Araucanía" },
        { url: "https://news.google.com/rss/search?q=site:Coquimbo+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "El Día" },
        { url: "https://news.google.com/rss/search?q=site:Aysén+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "el divisadero" },
        { url: "https://news.google.com/rss/search?q=site:mercurioantofagasta.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "El Mercurio de Antofagasta" },
        { url: "https://news.google.com/rss/search?q=site:elmercuriodepuertomontt.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "El Mercurio de Puerto Montt" },
        { url: "https://news.google.com/rss/search?q=site:Arica+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "El Morrocotudo.cl" },
        { url: "https://news.google.com/rss/search?q=site:elrancaguino.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "El Rancagüino" },
        { url: "https://news.google.com/rss/search?q=site:O'Higgins+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "El Tipógrafo" },
        { url: "https://news.google.com/rss/search?q=site:Antofagasta+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "FM Plus" },
        { url: "https://news.google.com/rss/search?q=site:itvpatagonia.com+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "ITV Patagonia" },
        { url: "https://news.google.com/rss/search?q=site:iquiquetv.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Iquique TV" },
        { url: "https://news.google.com/rss/search?q=site:Ñuble+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "La Discusión" },
        { url: "https://news.google.com/rss/search?q=site:estrellaIquique.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Estrella de Iquique" },
        { url: "https://news.google.com/rss/search?q=site:estrellavalpo.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "La Estrella de Valparaíso" },
        { url: "https://news.google.com/rss/search?q=site:Atacama+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Maray online" },
        { url: "https://news.google.com/rss/search?q=site:mauleopina.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Maule Opina" },
        { url: "https://news.google.com/rss/search?q=site:nubledigital.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Ñuble Digital" },
        { url: "https://news.google.com/rss/search?q=site:elpinguino.com+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Pingüino Multimedia/El Pingüino" },
        { url: "https://news.google.com/rss/search?q=site:Valparaíso+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Puranoticia.cl" },
        { url: "https://news.google.com/rss/search?q=site:Biobío+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Punto Siete" },
        { url: "https://news.google.com/rss/search?q=site:radioaraucana.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Araucana" },
        { url: "https://news.google.com/rss/search?q=site:radiobienvenida.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Bienvenida (O'Higgins)" },
        { url: "https://news.google.com/rss/search?q=site:carnaval.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Carnaval" },
        { url: "https://news.google.com/rss/search?q=site:radiocaramelo.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Caramelo (O'Higgins)" },
        { url: "https://news.google.com/rss/search?q=site:radiochillan.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Chillán" },
        { url: "https://news.google.com/rss/search?q=site:radiochiloe.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Chiloé" },
        { url: "https://news.google.com/rss/search?q=site:digitalfmarica.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Digital FM Arica" },
        { url: "https://news.google.com/rss/search?q=site:digitalfmvaldivia.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Digital FM Valdivia" },
        { url: "https://news.google.com/rss/search?q=site:radiofemenina.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Femenina (Biobío)" },
        { url: "https://news.google.com/rss/search?q=site:radiofestival.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Festival (Valparaíso)" },
        { url: "https://news.google.com/rss/search?q=site:radiofestiva.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Festiva (Atacama)" },
        { url: "https://news.google.com/rss/search?q=site:radiofutura.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Futura (Maule)" },
        { url: "https://news.google.com/rss/search?q=site:radiogen.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Gen (Aysén)" },
        { url: "https://news.google.com/rss/search?q=site:grado90.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Grado 90 (Tarapacá)" },
        { url: "https://news.google.com/rss/search?q=site:guayacanfm.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Guayacán FM (Coquimbo)" },
        { url: "https://news.google.com/rss/search?q=site:ilusionfm.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Ilusión FM (O'Higgins)" },
        { url: "https://news.google.com/rss/search?q=site:radiointeractiva.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Interactiva (Ñuble)" },
        { url: "https://news.google.com/rss/search?q=site:radioladiscusion.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio La Discusión (Ñuble)" },
        { url: "https://news.google.com/rss/search?q=site:radiomagallanes.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Magallanes" },
        { url: "https://news.google.com/rss/search?q=site:radiomadero.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Madero (Antofagasta)" },
        { url: "https://news.google.com/rss/search?q=site:radiomia.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Mía (Maule)" },
        { url: "https://news.google.com/rss/search?q=site:radiomirador.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Mirador (Araucanía)" },
        { url: "https://news.google.com/rss/search?q=site:montecarlo.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Montecarlo (Coquimbo)" },
        { url: "https://news.google.com/rss/search?q=site:radionatales.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Natales (Magallanes)" },
        { url: "https://news.google.com/rss/search?q=site:radioneura.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Neura Arica" },
        { url: "https://news.google.com/rss/search?q=site:nostalgia.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Nostalgia Iquique" },
        { url: "https://news.google.com/rss/search?q=site:radionuble.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Ñuble" },
        { url: "https://news.google.com/rss/search?q=site:radiopaloma.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Paloma (Maule)" },
        { url: "https://news.google.com/rss/search?q=site:radiopaulina.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Paulina (Arica)" },
        { url: "https://news.google.com/rss/search?q=site:radiopilmaiquen.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Pilmaiquén (Los Ríos)" },
        { url: "https://news.google.com/rss/search?q=site:radiopinguino.com+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Pingüino (Magallanes)" },
        { url: "https://news.google.com/rss/search?q=site:radiopuertanorte.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Puerta Norte (Arica)" },
        { url: "https://news.google.com/rss/search?q=site:radioreloncavi.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Reloncaví (Los Lagos)" },
        { url: "https://news.google.com/rss/search?q=site:radionuevotiempo.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio RT (Atacama)" },
        { url: "https://news.google.com/rss/search?q=site:radiorumbos.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Rumbos (O'Higgins)" },
        { url: "https://news.google.com/rss/search?q=site:sago.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Sago Osorno (Los Lagos)" },
        { url: "https://news.google.com/rss/search?q=site:radiosantamaria.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Santa María (Aysén)" },
        { url: "https://news.google.com/rss/search?q=site:radiosol.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Sol FM (Antofagasta)" },
        { url: "https://news.google.com/rss/search?q=site:radiouniversal.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Universal Temuco" },
        { url: "https://news.google.com/rss/search?q=site:radiovalparaiso.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Valparaíso" },
        { url: "https://news.google.com/rss/search?q=site:radioventisqueros.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Radio Ventisqueros (Aysén)" },
        { url: "https://news.google.com/rss/search?q=site:resumen.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Resumen.cl (Biobío)" },
        { url: "https://news.google.com/rss/search?q=site:rioenlinea.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Río en Línea (Los Ríos)" },
        { url: "https://news.google.com/rss/search?q=site:rtllinares.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "RTL Linares (Maule)" },
        { url: "https://news.google.com/rss/search?q=site:temucodiario.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Temuco Diario" },
        { url: "https://news.google.com/rss/search?q=site:timeline.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "Timeline.cl (Antofagasta)" },
        { url: "https://news.google.com/rss/search?q=site:elmercurio.com+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "El Mercurio" },
        { url: "https://news.google.com/rss/search?q=site:digital.elmercurio.com+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "El Mercurio (Digital)" },
        { url: "https://news.google.com/rss/search?q=site:elmercurio.com/Inversiones/+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "El Mercurio Inversiones" },
        { url: "https://news.google.com/rss/search?q=site:soychile.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419", sourceName: "SoyChile" },
        { url: 'https://news.google.com/rss/search?q=site:diariofutrono.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419', sourceName: 'Diario Futrono' },
        { url: 'https://news.google.com/rss/search?q=site:radiopolar.com+pesca&hl=es-CL&gl=CL&ceid=CL:es-419', sourceName: 'Radio Polar' },
        { url: 'https://news.google.com/rss/search?q=site:regionesnoticias.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419', sourceName: 'Regiones Noticias' },
        { url: 'https://news.google.com/rss/search?q=site:portalinnova.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419', sourceName: 'Portal Innova' },
        { url: 'https://news.google.com/rss/search?q=site:radio.uchile.cl+pesca&hl=es-CL&gl=CL&ceid=CL:es-419', sourceName: 'Radio Uchile' }
    ],
    sites: [
        {
            name: 'La Tercera',
            url: 'https://www.latercera.com/search/?q=pesca',
            selector: 'article, .card, h2, h3',
            titleSelector: 'a',
            linkSelector: 'a',
            summarySelector: '.deck, p'
        },
        {
            name: 'El Desconcierto',
            url: 'https://eldesconcierto.cl/?s=pesca',
            selector: 'article, .post, h2, h3',
            titleSelector: 'a',
            linkSelector: 'a',
            summarySelector: 'p, .excerpt'
        },
        {
            name: 'Interferencia',
            url: 'https://interferencia.cl/?s=pesca',
            selector: 'article, .post, h2, h3',
            titleSelector: 'a',
            linkSelector: 'a',
            summarySelector: 'p'
        },
        {
            name: 'El Observador',
            url: 'https://www.observador.cl/?s=pesca',
            selector: 'article, .post, h2, h3',
            titleSelector: 'a',
            linkSelector: 'a',
            summarySelector: 'p'
        },
        {
            name: 'Pura Noticia',
            url: 'https://puranoticia.pnt.cl/?s=pesca',
            selector: 'article, .post, h2, h3',
            titleSelector: 'a',
            linkSelector: 'a',
            summarySelector: 'p'
        },
        {
            name: 'Hora 12',
            url: 'https://www.hora12.cl/?s=pesca',
            selector: 'article, .post, h2, h3',
            titleSelector: 'a',
            linkSelector: 'a',
            summarySelector: 'p'
        },
        {
            name: 'Diario Talca',
            url: 'https://www.diariotalca.cl/?s=pesca',
            selector: 'article, .post, h2, h3',
            titleSelector: 'a',
            linkSelector: 'a',
            summarySelector: 'p'
        },
        {
            name: 'Diario Antofagasta',
            url: 'https://www.diarioantofagasta.cl/?s=pesca',
            selector: 'article, .post, h2, h3',
            titleSelector: 'a',
            linkSelector: 'a',
            summarySelector: 'p'
        },
        {
            name: 'Mundo Acuícola',
            url: 'https://www.mundoacuicola.cl/new/',
            selector: '.read-title, h4',
            titleSelector: 'a',
            linkSelector: 'a',
            summarySelector: 'p'
        },
        {
            name: 'El Mercurio Beta',
            url: 'https://beta.elmercurio.com',
            selector: 'body',
            titleSelector: 'a',
            linkSelector: 'a',
            summarySelector: 'p',
            isBetaMercurio: true
        }
    ]
};
